export const vars = {
  textPrimary: "var(--mui-palette-text-primary)",
  textSecondary: "var(--mui-palette-text-secondary)",
  backgroundDefault: "var(--mui-palette-background-default)",
  backgroundPaper: "var(--mui-palette-background-paper)",
  primaryMain: "var(--mui-palette-primary-main)",
  primaryDark: "var(--mui-palette-primary-dark)",
  primaryLight: "var(--mui-palette-primary-light)",
  secondaryMain: "var(--mui-palette-secondary-main)",
  secondaryLight: "var(--mui-palette-secondary-light)",
  divider: "var(--mui-palette-divider)",
  surface: "var(--mui-palette-custom-surface)",
  border: "var(--mui-palette-custom-border)",
  cardShadow: "var(--mui-palette-custom-cardShadow)",
  accentGradient: "var(--mui-palette-custom-accentGradient)",
  navScrolledBg: "var(--mui-palette-custom-navScrolledBg)",
  navScrolledBorder: "var(--mui-palette-custom-navScrolledBorder)",
  navScrolledShadow: "var(--mui-palette-custom-navScrolledShadow)",
  navInactive: "var(--mui-palette-custom-navInactive)",
  primarySoft: "var(--mui-palette-custom-primarySoft)",
  hoverOverlay: "var(--mui-palette-custom-hoverOverlay)",
  timelineTrack: "var(--mui-palette-custom-timelineTrack)",
  volunteer: "var(--mui-palette-custom-volunteer)",
  heroGlow: "var(--mui-palette-custom-heroGlow)",
  ctaGradient: "var(--mui-palette-custom-ctaGradient)",
} as const;
